version: '3.7'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: tFvnFf32obTMy86IuKryfOga5
      MYSQL_DATABASE: library
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - library

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD: tFvnFf32obTMy86IuKryfOga5
    command: redis-server --requirepass tFvnFf32obTMy86IuKryfOga5
    ports:
      - "6380:6379"
    networks:
      - library

networks:
  library:
    driver: bridge

volumes:
  mysql_data:
    driver: local
